#!/bin/bash

source cs_dirs

cd $HOME_DIR/projects

echo scanning all downloaded data
find $WWW_DOWNLOAD/csfirst.withgoogle.com/ -type f -exec grep scratch.mit.local/projects/ {} \; \
 | grep -o -E 'scratch.mit.local/projects/[0-9]+' | sed -e "s|scratch.mit.local|scratch.mit.edu|g" | sort -u > $HOME_DIR/projects/links.txt

find . -type d |grep "./"| sed -e "s|./|scratch.mit.edu/projects/|" | sort -u > existing_links.txt

diff existing_links.txt $HOME_DIR/projects/links.txt |grep ">" | sed -e "s/> //" > $HOME_DIR/projects/missing.txt

echo Missing projects:
cat $HOME_DIR/projects/missing.txt

