#!/bin/bash

source cs_dirs

cd $HOME_DIR
git pull

mkdir -p $WWW
cd $WWW

rm -rf $WWW_DOWNLOAD

node --max-old-space-size=3072 $HOME_DIR/scripts/scraper.js
node --max-old-space-size=3072 $HOME_DIR/scripts/download_css_fonts.js

cd $WWW_DOWNLOAD
node --max-old-space-size=3072 $HOME_DIR/scripts/mirror.js

mkdir $WWW_DOWNLOAD/www.google-analytics.com
cp $HOME_DIR/data/analytics.js $WWW_DOWNLOAD/www.google-analytics.com/

cd $WWW_DOWNLOAD
bash ../download_fonts.sh
bash ../download.sh
